// src/app/home/home.component.ts
import { Component, OnInit } from "@angular/core";
import { Title, Meta } from "@angular/platform-browser";

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.css"]
})
export class HomeComponent implements OnInit {
  title = "Home Page - Zen van Riel";
  constructor(private titleService: Title, private metaService: Meta) {}
  ngOnInit() {
    this.titleService.setTitle(this.title);
    this.metaService.addTags([
      { name: "keywords", content: "Zen van Riel, Zen, Riel" },
      {
        name: "description",
        content:
          "This site serves as a small portfolio to post about some of my work."
      },
      { name: "robots", content: "index, follow" }
    ]);
  }
}

<div class="container">
  <h1>My Blog Page</h1>
  <div style="padding: 10px 0px;" *ngFor="let blog of blogs">
    <div class="card">
      <div class="card-header">
        Featured
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ blog.title }}</h5>
        <p class="card-text">
          {{ blog.content }}
        </p>
      </div>
    </div>
  </div>
</div>

// src/pages/home.tsx
import React from "react";
import {RouteComponentProps} from "@reach/router";
import DefaultNavbar from "../components/DefaultNavbar";
import Metadata from "../components/Metadata";

export default class Home extends React.Component<RouteComponentProps> {
  render() {
    return (
      <div>
        <Metadata
          title={"Zen van Riel - Home Page"}
          description={
            "This site serves as a small portfolio to post about some of my work."
          }
        />
        <DefaultNavbar />
        <p>home</p>
      </div>
    );
  }
}
